In [2]:
import numpy as np

In [3]:
A = np.array([[1,-1],[1,0]])
A

array([[ 1, -1],
       [ 1,  0]])

In [16]:
vector = np.array([1,1])
vector

array([1, 1])

In [8]:
np.dot(A, vector)

array([0, 1])

In [11]:
from numpy.linalg import eig
w,v=eig(A)
print('E-value:', w)
print('E-vector', v)

E-value: [0.5+0.8660254j 0.5-0.8660254j]
E-vector [[0.35355339+0.61237244j 0.35355339-0.61237244j]
 [0.70710678+0.j         0.70710678-0.j        ]]


In [12]:
A = np.array([[2,1],[1,2]])
A

array([[2, 1],
       [1, 2]])

In [13]:
w,v=eig(A)
print('E-value:', w)
print('E-vector', v)

E-value: [3. 1.]
E-vector [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [19]:
rotate = np.array([[0, -1], [1,0]])
np.dot(rotate, vector)

array([-1,  1])

In [20]:
sheer = np.array([[1, 1], [0,1]])
np.dot(sheer, np.dot(rotate, vector))

array([0, 1])