# <font color = 'green'> Getting started
https://scikit-learn.org/stable/getting_started.html

# Fitting and predicting: estimator basics
<img src='https://media.istockphoto.com/photos/this-one-match-perfect-with-me-picture-id1293366109?b=1&k=20&m=1293366109&s=170667a&w=0&h=2z_h2WlM3291IRKFXrdmtObnCt93rNNdNN6mqvnKD1I='>

In [61]:
from sklearn.ensemble import RandomForestClassifier

In [62]:
clf = RandomForestClassifier()

In [63]:
X = [[1,2,3], [11,12,13]]
X

[[1, 2, 3], [11, 12, 13]]

In [64]:
X = ((1,2,3), (11,12,13))
X

((1, 2, 3), (11, 12, 13))

In [65]:
import numpy as np
X = np.array(X)
print(X)
X.shape

[[ 1  2  3]
 [11 12 13]]


(2, 3)

In [66]:
import pandas as pd
X = pd.DataFrame(X)
X

0   1   2
0   1   2   3
1  11  12  13

In [67]:
y=[0,1]

In [68]:
clf.fit(X,y)

RandomForestClassifier()

In [69]:
clf.predict(X)

array([0, 1])

In [70]:
clf.predict([[4,5,6]])

array([0])

In [71]:
clf.predict(np.array([4,5,6]).reshape(1,-1))

array([0])

In [72]:
np.array([4,5,6]).reshape(1,-1).shape

(1, 3)

In [73]:
from sklearn.datasets import load_iris
X, y = load_iris(return_X_y=True)

In [74]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [75]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [76]:
new_instance = [[2,4,1,2]]

In [77]:
clf.fit(X,y)

RandomForestClassifier()

In [78]:
clf.predict(new_instance)

array([0])

In [79]:
np.isclose(clf.predict(X), y)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [80]:
X.shape

(150, 4)

In [81]:
X_train = X[0:100, ]; X_test = X[100:, ]
y_train = y[0:100]; y_test = y[100:]

In [82]:
clf.fit(X_train,y_train)

RandomForestClassifier()

# Model evaluation
<img src='https://images.unsplash.com/photo-1543728069-a3f97c5a2f32?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8ZmFzaGlvbiUyMHNob3d8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60'>

In [83]:
clf.predict(X_test)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [84]:
y_test

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2])

In [85]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [86]:
X_train = X[0:100, ]; X_test = X[100:, ]
y_train = y[0:100]; y_test = y[100:]

In [87]:
X_train_index = np.random.randint(0, 150, 100)
X_train_index

array([ 27,  31,  78,  71,  95, 113,  64,  91, 102, 121, 149,  36,  81,
         9, 126, 128,  13,  65, 107,  57, 115,  35,  83,  56, 141,  82,
        43,  41,  22, 135, 128, 147, 117,  49, 132,  28,  82,  29,  66,
        36,  80,  17,  11, 133,  42, 100,  72,  33,  15,  45, 119,   6,
        32, 121,  69,  95, 115, 149,  58, 134,   4,  31,   5,  33, 116,
        98, 113,  28,  28, 130,  55,  80,  88, 115,  41,  91, 132,  56,
       130, 137, 141, 139,  21,  12, 109,  56,  25,  57,  65,  92,  49,
       139, 129,  22, 102,  13,  84,  99,  30,  13])

In [88]:
np.isin(np.arange(0,150), X_train_index)

array([False, False, False, False,  True,  True,  True, False, False,
        True, False,  True,  True,  True, False,  True, False,  True,
       False, False, False,  True,  True, False, False,  True, False,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True, False, False, False, False,  True,  True,  True, False,
        True, False, False, False,  True, False, False, False, False,
       False,  True,  True,  True,  True, False, False, False, False,
       False,  True,  True,  True, False, False,  True, False,  True,
        True, False, False, False, False, False,  True, False,  True,
        True,  True,  True,  True, False, False, False,  True, False,
       False,  True,  True, False, False,  True, False, False,  True,
        True,  True, False,  True, False, False, False, False,  True,
       False,  True, False, False, False,  True, False,  True,  True,
        True, False,  True, False,  True, False, False, False, False,
        True, False,

In [89]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [90]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
X_train.shape
X_test.shape

(112, 4)

(38, 4)

In [91]:
clf.fit(X_train,y_train)

RandomForestClassifier()

In [92]:
clf.predict(X_test)

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2])

In [93]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1])

In [94]:
from sklearn.metrics import accuracy_score

In [95]:
accuracy_score(clf.predict(X_test), y_test)

0.9736842105263158

In [96]:
np.isclose(clf.predict(X_test), y_test)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False])

In [97]:
1 - 1/len(y_test)

0.9736842105263158

In [98]:
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

In [99]:
clf.set_params(n_estimators = 1, max_depth =1)

RandomForestClassifier(max_depth=1, n_estimators=1)

In [100]:
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': 1,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 1,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [101]:
clf.predict(X_test)

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2])

In [102]:
accuracy_score(clf.predict(X_test), y_test)

0.9736842105263158

# cross validation
<img src = 'https://scikit-learn.org/stable/_images/grid_search_cross_validation.png' width=600 height=300>

In [103]:
load_iris()

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [104]:
load_iris().keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [105]:
df = pd.DataFrame(load_iris()['data'], columns = load_iris()['feature_names'])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [106]:
df['target'] = load_iris()['target']
df.head()
df.shape

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

(150, 5)

In [107]:
from sklearn.model_selection import cross_validate
#lr = LinearRegression()
X = df.drop(['target'], axis=1)
y = df.target

result = cross_validate(clf, X, y)  # defaults to 5-fold CV
result['test_score']  # r_squared score is high because dataset is easy

array([0.66666667, 0.66666667, 0.5       , 0.56666667, 0.66666667])

In [108]:
from sklearn.model_selection import cross_validate
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
result = cross_validate(lr, X, y)  # defaults to 5-fold CV
result['test_score']  # r_squared score is high because dataset is easy

array([0.        , 0.85124923, 0.        , 0.76155439, 0.        ])

In [109]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
result = cross_validate(lr, X, y)  # defaults to 5-fold CV
result['test_score'] 

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

# hyperparameter
https://scikit-learn.org/stable/modules/cross_validation.html#cross-validation
<img src='https://scikit-learn.org/stable/_images/grid_search_workflow.png' width=600 height=300>

# RandomizedsearchCV
<img src='https://media.istockphoto.com/photos/explorer-in-the-field-picture-id157180213?b=1&k=20&m=157180213&s=170667a&w=0&h=v6UYlB3gRWEmnwhDfIHtLkBbVvG4Bd4ssa-B74uRi-I='>

In [110]:
from sklearn.datasets import fetch_california_housing
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
from scipy.stats import randint

X, y = fetch_california_housing(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
##############################################################################
# define the parameter space that will be searched over
param_distributions = {'n_estimators': randint(1, 5),
                       'max_depth': randint(5, 10)}

# now create a searchCV object and fit it to the data
search = RandomizedSearchCV(estimator=RandomForestRegressor(random_state=0),
                            n_iter=5,
                            param_distributions=param_distributions,
                            #cv = 3,
                            random_state=0)
search.fit(X_train, y_train)
##############################################################################

RandomizedSearchCV(estimator=RandomForestRegressor(random_state=0), n_iter=5,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_frozen object at 0x0000022DD78C4370>,
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_frozen object at 0x0000022DDCB16670>},
                   random_state=0)

In [111]:
search.best_params_
search.cv_results_
pd.DataFrame(search.cv_results_)
# the search object now acts like a normal random forest estimator
# with max_depth=9 and n_estimators=4
search.score(X_test, y_test)

{'max_depth': 9, 'n_estimators': 4}

{'mean_fit_time': array([0.13045459, 0.08117604, 0.12026753, 0.09355397, 0.02712755]),
 'std_fit_time': array([0.00097205, 0.00233054, 0.00279624, 0.00098247, 0.00039712]),
 'mean_score_time': array([0.00179119, 0.00120883, 0.00160284, 0.00158701, 0.00100775]),
 'std_score_time': array([3.97731683e-04, 3.93394684e-04, 4.90134451e-04, 4.81269445e-04,
        1.97570616e-05]),
 'param_max_depth': masked_array(data=[9, 5, 8, 6, 7],
              mask=[False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_n_estimators': masked_array(data=[4, 4, 4, 4, 1],
              mask=[False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'max_depth': 9, 'n_estimators': 4},
  {'max_depth': 5, 'n_estimators': 4},
  {'max_depth': 8, 'n_estimators': 4},
  {'max_depth': 6, 'n_estimators': 4},
  {'max_depth': 7, 'n_estimators': 1}],
 'split0_test_score': array([0.73465399, 0.65701053, 0.72348595, 0.68581474, 0.6464561 

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.130455      0.000972         0.001791        0.000398   
1       0.081176      0.002331         0.001209        0.000393   
2       0.120268      0.002796         0.001603        0.000490   
3       0.093554      0.000982         0.001587        0.000481   
4       0.027128      0.000397         0.001008        0.000020   

  param_max_depth param_n_estimators                               params  \
0               9                  4  {'max_depth': 9, 'n_estimators': 4}   
1               5                  4  {'max_depth': 5, 'n_estimators': 4}   
2               8                  4  {'max_depth': 8, 'n_estimators': 4}   
3               6                  4  {'max_depth': 6, 'n_estimators': 4}   
4               7                  1  {'max_depth': 7, 'n_estimators': 1}   

   split0_test_score  split1_test_score  split2_test_score  split3_test_score  \
0           0.734654           0.713268           0.747847           0.748488   
1           0.657011           0.626846           0.670513           0.669692   
2           0.723486           0.703786           0.740555           0.735182   
3           0.685815           0.660283           0.702731           0.698675   
4           0.646456           0.651310           0.677519           0.644392   

   split4_test_score  mean_test_score  std_test_score  rank_test_score  
0           0.730195         0.734890        0.012980                1  
1           0.655614         0.655935        0.015806                4  
2           0.720915         0.724785        0.012763                2  
3           0.684175         0.686336        0.014864                3  
4           0.629082         0.649752        0.015750                5

0.735363411343253

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.RandomizedSearchCV.html

In [112]:
search.get_params()

{'cv': None,
 'error_score': nan,
 'estimator__bootstrap': True,
 'estimator__ccp_alpha': 0.0,
 'estimator__criterion': 'mse',
 'estimator__max_depth': None,
 'estimator__max_features': 'auto',
 'estimator__max_leaf_nodes': None,
 'estimator__max_samples': None,
 'estimator__min_impurity_decrease': 0.0,
 'estimator__min_impurity_split': None,
 'estimator__min_samples_leaf': 1,
 'estimator__min_samples_split': 2,
 'estimator__min_weight_fraction_leaf': 0.0,
 'estimator__n_estimators': 100,
 'estimator__n_jobs': None,
 'estimator__oob_score': False,
 'estimator__random_state': 0,
 'estimator__verbose': 0,
 'estimator__warm_start': False,
 'estimator': RandomForestRegressor(random_state=0),
 'iid': 'deprecated',
 'n_iter': 5,
 'n_jobs': None,
 'param_distributions': {'n_estimators': <scipy.stats._distn_infrastructure.rv_frozen at 0x22ddcb16670>,
  'max_depth': <scipy.stats._distn_infrastructure.rv_frozen at 0x22dd78c4370>},
 'pre_dispatch': '2*n_jobs',
 'random_state': 0,
 'refit': True,


# Transformers and pre-processors
<img src='https://images.unsplash.com/photo-1618945524163-32451704cbb8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8dHJhbnNmb3JtZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60'>

In [113]:
from sklearn.preprocessing import StandardScaler
X = [[0, 15],
     [1, -10]]

# scale data according to computed scaling values
StandardScaler().fit(X).transform(X)

array([[-1.,  1.],
       [ 1., -1.]])

# Pipelines: chaining pre-processors and estimators
<img src='https://images.unsplash.com/photo-1553159925-02b2e24f471d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2067&q=80' width=600 height=300>

In [114]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline

# create a pipeline object
pipe = make_pipeline(
    StandardScaler(),
    LogisticRegression()
)

# load the iris dataset and split it into train and test sets
X, y = load_iris(return_X_y=True)
X[:, 2] = X[:, 2]*100

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# fit the whole pipeline
pipe.fit(X_train, y_train)


# we can now use it like any other estimator
accuracy_score(pipe.predict(X_test), y_test)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

0.9736842105263158

# Pipelines: hyperparameters

In [115]:
X, y = fetch_california_housing(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
##############################################################################
# define the parameter space that will be searched over

# create a pipeline object
pipe = make_pipeline(
    StandardScaler(),
    RandomForestRegressor(random_state=0)
)

param_distributions = {'n_estimators': randint(1, 5),
                       'max_depth': randint(5, 10)}

# now create a searchCV object and fit it to the data
search = RandomizedSearchCV(estimator= pipe,
                            n_iter=5,
                            param_distributions=param_distributions,
                            #cv = 3,
                            random_state=0)
search.fit(X_train, y_train)
##############################################################################

ValueError: Invalid parameter max_depth for estimator Pipeline(steps=[('standardscaler', StandardScaler()),
                ('randomforestregressor',
                 RandomForestRegressor(random_state=0))]). Check the list of available parameters with `estimator.get_params().keys()`.

In [123]:
X, y = fetch_california_housing(return_X_y=True)
X[:, 2] = X[:, 2]*10000

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
##############################################################################
# define the parameter space that will be searched over

# create a pipeline object
pipe = make_pipeline(
    StandardScaler(),
    RandomForestRegressor(random_state=0)
)

param_distributions = {'randomforestregressor__n_estimators': randint(1, 5),
                       'randomforestregressor__max_depth': randint(5, 10)}

# now create a searchCV object and fit it to the data
search = RandomizedSearchCV(estimator= pipe,
                            n_iter=5,
                            param_distributions=param_distributions,
                            #cv = 3,
                            random_state=0)
search.fit(X_train, y_train)
##############################################################################

RandomizedSearchCV(estimator=Pipeline(steps=[('standardscaler',
                                              StandardScaler()),
                                             ('randomforestregressor',
                                              RandomForestRegressor(random_state=0))]),
                   n_iter=5,
                   param_distributions={'randomforestregressor__max_depth': <scipy.stats._distn_infrastructure.rv_frozen object at 0x0000022DD6681040>,
                                        'randomforestregressor__n_estimators': <scipy.stats._distn_infrastructure.rv_frozen object at 0x0000022DDCB1AB50>},
                   random_state=0)

In [124]:
search.score(X_test, y_test)

0.7354483324284191

# The performance of model depends on data patterns.
https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html

In [147]:
from sklearn.datasets import load_digits
from sklearn.linear_model import Perceptron
from sklearn.neural_network import MLPClassifier

X, y = load_digits(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y,
                                                    random_state=1)
estimators = [LogisticRegression(), RandomForestClassifier(random_state=0), 
              Perceptron(tol=1e-3, random_state=0), MLPClassifier(random_state=1, max_iter=300)]

for estimator in estimators:
    estimator.fit(X_train, y_train)
    estimator.score(X_test, y_test)

LogisticRegression()

0.9666666666666667

RandomForestClassifier(random_state=0)

0.9622222222222222

Perceptron()

0.9533333333333334

MLPClassifier(max_iter=300, random_state=1)

0.9688888888888889

In [148]:
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

for estimator in estimators:
    estimator.fit(X_train, y_train)
    estimator.score(X_test, y_test)

LogisticRegression()

0.9736842105263158

RandomForestClassifier(random_state=0)

0.9736842105263158

Perceptron()

0.868421052631579

MLPClassifier(max_iter=300, random_state=1)

0.9473684210526315

# End