# Working With Text Data

In [1]:
# 명령 결과 모두 보기
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

# 버전 경고 무시
import warnings
warnings.filterwarnings('ignore')

# 판다스와 넘피
import pandas as pd
import numpy as np

# 그림 그리기
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
get_ipython().run_line_magic('matplotlib', 'inline')
plt.rcParams['font.family']='Malgun Gothic' # 한글폰트

In [2]:
def summary(df) :
    tf = pd.DataFrame({'데이터형태(dtypes)' : df.dtypes,
                       '비 결측치 수(notnull': df.notnull().sum(),
                       '결측치 수(null)' : df.isnull().sum(),
                       '고유값 수(nunique)' : df.nunique()})
    return tf

# Loading the 20 newsgroups dataset

In [3]:
categories = ['alt.atheism', 'soc.religion.christian',
              'comp.graphics', 'sci.med']

In [4]:
from sklearn.datasets import fetch_20newsgroups
twenty_train = fetch_20newsgroups(subset='train',
    categories=categories, shuffle=True, random_state=42)
type(twenty_train)

sklearn.utils.Bunch

In [5]:
twenty_train.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])

In [6]:
twenty_train.target_names
len(twenty_train.data)
len(twenty_train.filenames)

['alt.atheism', 'comp.graphics', 'sci.med', 'soc.religion.christian']

2257

2257

In [7]:
df = pd.DataFrame(twenty_train.data, columns = ['twenty_train.filenames'])
df['target'] = twenty_train.target
df.head()

twenty_train.filenames  target
0  From: sd345@city.ac.uk (Michael Collier)\nSubj...       1
1  From: ani@ms.uky.edu (Aniruddha B. Deglurkar)\...       1
2  From: djohnson@cs.ucsd.edu (Darin Johnson)\nSu...       3
3  From: s0612596@let.rug.nl (M.M. Zwart)\nSubjec...       3
4  From: stanly@grok11.columbiasc.ncr.com (stanly...       3

In [8]:
twenty_train.target_names
np.unique(twenty_train.target)

['alt.atheism', 'comp.graphics', 'sci.med', 'soc.religion.christian']

array([0, 1, 2, 3], dtype=int64)

In [9]:
match_dict = dict(zip(np.unique(twenty_train.target), twenty_train.target_names))
match_dict

{0: 'alt.atheism',
 1: 'comp.graphics',
 2: 'sci.med',
 3: 'soc.religion.christian'}

In [10]:
df['target'].map(match_dict)

0                comp.graphics
1                comp.graphics
2       soc.religion.christian
3       soc.religion.christian
4       soc.religion.christian
                 ...          
2252                   sci.med
2253                   sci.med
2254                   sci.med
2255                   sci.med
2256                   sci.med
Name: target, Length: 2257, dtype: object

In [11]:
df['target'] = df['target'].map(match_dict)
df.head()

twenty_train.filenames                  target
0  From: sd345@city.ac.uk (Michael Collier)\nSubj...           comp.graphics
1  From: ani@ms.uky.edu (Aniruddha B. Deglurkar)\...           comp.graphics
2  From: djohnson@cs.ucsd.edu (Darin Johnson)\nSu...  soc.religion.christian
3  From: s0612596@let.rug.nl (M.M. Zwart)\nSubjec...  soc.religion.christian
4  From: stanly@grok11.columbiasc.ncr.com (stanly...  soc.religion.christian

In [12]:
twenty_train.data[0]
twenty_train.data[0].split('\n') # text to list
twenty_train.data[0].split('\n')[:3]
'\n'.join(twenty_train.data[0].split('\n')[:3]) # list to text
',    '.join(twenty_train.data[0].split('\n')[:3])

'From: sd345@city.ac.uk (Michael Collier)\nSubject: Converting images to HP LaserJet III?\nNntp-Posting-Host: hampton\nOrganization: The City University\nLines: 14\n\nDoes anyone know of a good way (standard PC application/PD utility) to\nconvert tif/img/tga files into LaserJet III format.  We would also like to\ndo the same, converting to HPGL (HP plotter) files.\n\nPlease email any response.\n\nIs this the correct group?\n\nThanks in advance.  Michael.\n-- \nMichael Collier (Programmer)                 The Computer Unit,\nEmail: M.P.Collier@uk.ac.city                The City University,\nTel: 071 477-8000 x3769                      London,\nFax: 071 477-8565                            EC1V 0HB.\n'

['From: sd345@city.ac.uk (Michael Collier)',
 'Subject: Converting images to HP LaserJet III?',
 'Nntp-Posting-Host: hampton',
 'Organization: The City University',
 'Lines: 14',
 '',
 'Does anyone know of a good way (standard PC application/PD utility) to',
 'convert tif/img/tga files into LaserJet III format.  We would also like to',
 'do the same, converting to HPGL (HP plotter) files.',
 '',
 'Please email any response.',
 '',
 'Is this the correct group?',
 '',
 'Thanks in advance.  Michael.',
 '-- ',
 'Michael Collier (Programmer)                 The Computer Unit,',
 'Email: M.P.Collier@uk.ac.city                The City University,',
 'Tel: 071 477-8000 x3769                      London,',
 'Fax: 071 477-8565                            EC1V 0HB.',
 '']

['From: sd345@city.ac.uk (Michael Collier)',
 'Subject: Converting images to HP LaserJet III?',
 'Nntp-Posting-Host: hampton']

'From: sd345@city.ac.uk (Michael Collier)\nSubject: Converting images to HP LaserJet III?\nNntp-Posting-Host: hampton'

'From: sd345@city.ac.uk (Michael Collier),    Subject: Converting images to HP LaserJet III?,    Nntp-Posting-Host: hampton'

In [13]:
print("\n".join(twenty_train.data[0].split("\n")[:3]))

From: sd345@city.ac.uk (Michael Collier)
Subject: Converting images to HP LaserJet III?
Nntp-Posting-Host: hampton


In [14]:
print(twenty_train.target_names[twenty_train.target[0]])

comp.graphics


In [15]:
twenty_train.target[:10]

array([1, 1, 3, 3, 3, 3, 3, 2, 2, 2], dtype=int64)

In [16]:
for t in twenty_train.target[:10]:
    print(twenty_train.target_names[t])

comp.graphics
comp.graphics
soc.religion.christian
soc.religion.christian
soc.religion.christian
soc.religion.christian
soc.religion.christian
sci.med
sci.med
sci.med


# Extracting features from text files
## Bags of words
## Tokenizing text with scikit-learn

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()

X_train_counts = count_vect.fit_transform(twenty_train.data)
X_train_counts
X_train_counts.shape

<2257x35788 sparse matrix of type '<class 'numpy.int64'>'
	with 365886 stored elements in Compressed Sparse Row format>

(2257, 35788)

In [20]:
X_train_counts.toarray()
pd.DataFrame(X_train_counts.toarray())

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

0      1      2      3      4      5      6      7      8      9      \
0         0      0      0      0      0      0      0      0      0      0   
1         0      0      0      0      0      0      0      0      0      0   
2         0      0      0      0      0      0      0      0      0      0   
3         0      0      0      0      0      0      0      0      0      0   
4         1      0      0      0      0      0      0      0      0      0   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
2252      0      0      0      0      0      0      0      1      0      0   
2253      0      0      0      0      0      0      0      0      0      0   
2254      0      0      0      0      0      0      0      0      0      0   
2255      0      0      0      0      0      0      0      0      0      0   
2256      0      0      0      0      0      0      0      0      0      0   

      ...  35778  35779  35780  35781  35782  35783  35784  35785  35786  \
0     ...      0      0      0      0      0      0      0      0      0   
1     ...      0      0      0      0      0      0      0      0      0   
2     ...      0      0      0      0      0      0      0      0      0   
3     ...      0      0      2      0      0      0      0      0      0   
4     ...      0      0      0      0      0      0      0      0      0   
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
2252  ...      0      0      0      0      0      0      0      0      0   
2253  ...      0      0      0      0      0      0      0      0      0   
2254  ...      0      0      0      0      0      0      0      0      0   
2255  ...      0      0      0      0      0      0      0      0      0   
2256  ...      0      0      0      0      0      0      0      0      0   

      35787  
0         0  
1         0  
2         0  
3         0  
4         0  
...     ...  
2252      0  
2253      0  
2254      0  
2255      0  
2256      0  

[2257 rows x 35788 columns]

CountVectorizer supports counts of N-grams of words or consecutive characters. Once fitted, the vectorizer has built a dictionary of feature indices:

In [22]:
count_vect.vocabulary_.get('algorithm')

4690

## From occurrences to frequencies

In [23]:
from sklearn.feature_extraction.text import TfidfTransformer
tf_transformer = TfidfTransformer(use_idf=False).fit(X_train_counts)
X_train_tf = tf_transformer.transform(X_train_counts)
X_train_tf.shape

(2257, 35788)

In [24]:
X_train_tf.toarray()
pd.DataFrame(X_train_tf.toarray())

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

0      1      2      3      4      5      6         7      8      \
0     0.000000    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
1     0.000000    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
2     0.000000    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
3     0.000000    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
4     0.048622    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
...        ...    ...    ...    ...    ...    ...    ...       ...    ...   
2252  0.000000    0.0    0.0    0.0    0.0    0.0    0.0  0.069338    0.0   
2253  0.000000    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
2254  0.000000    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
2255  0.000000    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
2256  0.000000    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   

      9      ...  35778  35779    35780  35781  35782  35783  35784  35785  \
0       0.0  ...    0.0    0.0  0.00000    0.0    0.0    0.0    0.0    0.0   
1       0.0  ...    0.0    0.0  0.00000    0.0    0.0    0.0    0.0    0.0   
2       0.0  ...    0.0    0.0  0.00000    0.0    0.0    0.0    0.0    0.0   
3       0.0  ...    0.0    0.0  0.15523    0.0    0.0    0.0    0.0    0.0   
4       0.0  ...    0.0    0.0  0.00000    0.0    0.0    0.0    0.0    0.0   
...     ...  ...    ...    ...      ...    ...    ...    ...    ...    ...   
2252    0.0  ...    0.0    0.0  0.00000    0.0    0.0    0.0    0.0    0.0   
2253    0.0  ...    0.0    0.0  0.00000    0.0    0.0    0.0    0.0    0.0   
2254    0.0  ...    0.0    0.0  0.00000    0.0    0.0    0.0    0.0    0.0   
2255    0.0  ...    0.0    0.0  0.00000    0.0    0.0    0.0    0.0    0.0   
2256    0.0  ...    0.0    0.0  0.00000    0.0    0.0    0.0    0.0    0.0   

      35786  35787  
0       0.0    0.0  
1       0.0    0.0  
2       0.0    0.0  
3       0.0    0.0  
4       0.0    0.0  
...     ...    ...  
2252    0.0    0.0  
2253    0.0    0.0  
2254    0.0    0.0  
2255    0.0    0.0  
2256    0.0    0.0  

[2257 rows x 35788 columns]

In [25]:
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
X_train_tfidf.shape

(2257, 35788)

In [26]:
X_train_tf.toarray()
pd.DataFrame(X_train_tf.toarray())

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

0      1      2      3      4      5      6         7      8      \
0     0.000000    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
1     0.000000    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
2     0.000000    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
3     0.000000    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
4     0.048622    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
...        ...    ...    ...    ...    ...    ...    ...       ...    ...   
2252  0.000000    0.0    0.0    0.0    0.0    0.0    0.0  0.069338    0.0   
2253  0.000000    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
2254  0.000000    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
2255  0.000000    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   
2256  0.000000    0.0    0.0    0.0    0.0    0.0    0.0  0.000000    0.0   

      9      ...  35778  35779    35780  35781  35782  35783  35784  35785  \
0       0.0  ...    0.0    0.0  0.00000    0.0    0.0    0.0    0.0    0.0   
1       0.0  ...    0.0    0.0  0.00000    0.0    0.0    0.0    0.0    0.0   
2       0.0  ...    0.0    0.0  0.00000    0.0    0.0    0.0    0.0    0.0   
3       0.0  ...    0.0    0.0  0.15523    0.0    0.0    0.0    0.0    0.0   
4       0.0  ...    0.0    0.0  0.00000    0.0    0.0    0.0    0.0    0.0   
...     ...  ...    ...    ...      ...    ...    ...    ...    ...    ...   
2252    0.0  ...    0.0    0.0  0.00000    0.0    0.0    0.0    0.0    0.0   
2253    0.0  ...    0.0    0.0  0.00000    0.0    0.0    0.0    0.0    0.0   
2254    0.0  ...    0.0    0.0  0.00000    0.0    0.0    0.0    0.0    0.0   
2255    0.0  ...    0.0    0.0  0.00000    0.0    0.0    0.0    0.0    0.0   
2256    0.0  ...    0.0    0.0  0.00000    0.0    0.0    0.0    0.0    0.0   

      35786  35787  
0       0.0    0.0  
1       0.0    0.0  
2       0.0    0.0  
3       0.0    0.0  
4       0.0    0.0  
...     ...    ...  
2252    0.0    0.0  
2253    0.0    0.0  
2254    0.0    0.0  
2255    0.0    0.0  
2256    0.0    0.0  

[2257 rows x 35788 columns]

## Training a classifier

In [27]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(X_train_tfidf, twenty_train.target)

In [28]:
docs_new = ['God is love', 'OpenGL on the GPU is fast']
X_new_counts = count_vect.transform(docs_new)
X_new_tfidf = tfidf_transformer.transform(X_new_counts)

predicted = clf.predict(X_new_tfidf)

for doc, category in zip(docs_new, predicted):
    print('%r => %s' % (doc, twenty_train.target_names[category]))

'God is love' => soc.religion.christian
'OpenGL on the GPU is fast' => comp.graphics


## Building a pipeline

In [29]:
from sklearn.pipeline import Pipeline
text_clf = Pipeline([
    ('vect', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('clf', MultinomialNB()),
])

In [30]:
text_clf.fit(twenty_train.data, twenty_train.target)

Pipeline(steps=[('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                ('clf', MultinomialNB())])

## Evaluation of the performance on the test set

In [31]:
import numpy as np
twenty_test = fetch_20newsgroups(subset='test',
    categories=categories, shuffle=True, random_state=42)
docs_test = twenty_test.data
predicted = text_clf.predict(docs_test)
np.mean(predicted == twenty_test.target)

0.8348868175765646

In [32]:
from sklearn.linear_model import SGDClassifier
text_clf = Pipeline([
    ('vect', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('clf', SGDClassifier(loss='hinge', penalty='l2',
                          alpha=1e-3, random_state=42,
                          max_iter=5, tol=None)),
])

text_clf.fit(twenty_train.data, twenty_train.target)

predicted = text_clf.predict(docs_test)
np.mean(predicted == twenty_test.target)

Pipeline(steps=[('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                ('clf',
                 SGDClassifier(alpha=0.001, max_iter=5, random_state=42,
                               tol=None))])

0.9101198402130493

In [33]:
from sklearn import metrics
print(metrics.classification_report(twenty_test.target, predicted,
    target_names=twenty_test.target_names))

metrics.confusion_matrix(twenty_test.target, predicted)

                        precision    recall  f1-score   support

           alt.atheism       0.95      0.80      0.87       319
         comp.graphics       0.87      0.98      0.92       389
               sci.med       0.94      0.89      0.91       396
soc.religion.christian       0.90      0.95      0.93       398

              accuracy                           0.91      1502
             macro avg       0.91      0.91      0.91      1502
          weighted avg       0.91      0.91      0.91      1502



array([[256,  11,  16,  36],
       [  4, 380,   3,   2],
       [  5,  35, 353,   3],
       [  5,  11,   4, 378]], dtype=int64)

## Parameter tuning using grid search

In [34]:
from sklearn.model_selection import GridSearchCV
parameters = {
    'vect__ngram_range': [(1, 1), (1, 2)],
    'tfidf__use_idf': (True, False),
    'clf__alpha': (1e-2, 1e-3),
}

In [35]:
gs_clf = GridSearchCV(text_clf, parameters, cv=5, n_jobs=-1)

In [36]:
gs_clf = gs_clf.fit(twenty_train.data[:400], twenty_train.target[:400])

In [37]:
twenty_train.target_names[gs_clf.predict(['God is love'])[0]]

'soc.religion.christian'

In [38]:
gs_clf.best_score_

for param_name in sorted(parameters.keys()):
    print("%s: %r" % (param_name, gs_clf.best_params_[param_name]))

0.9175000000000001

clf__alpha: 0.001
tfidf__use_idf: True
vect__ngram_range: (1, 1)


# End